language: ruby
before_install: gem install bundler
bundler_args: --without guard
script: "bundle exec rake ci"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
  - ruby-head
  - jruby-head
notifications:
  email:
    - dan.kubb@gmail.com
    - mbj@seonic.net
