language: ruby
cache: bundler
bundler_args: --without yard guard benchmarks
script: "bundle exec rake ci"
rvm:
  - ree
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0-rc1
  - ruby-head
  - rbx
matrix:
  include:
    - rvm: jruby-18mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
    - rvm: jruby-20mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"  # for simplecov
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
    - rvm: jruby-head
  fast_finish: true
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
